[print(f'- {getattr(list,r).__doc__}') for r in dir(list) if not r.__contains__('_')]
print(f'''{'='*30}\n Append''')
list_a = []
list_a.append(1)
list_a.append('dua')
list_a.append(3.0)
list_a.append(4+1j)
print(f'{list_a}')
print(f'''{'='*30}\nclear''')
list_a.clear()
print(f'{list_a}')
list_a = [1, 'dua', 3.0, 4+1j]
print(f'{list_a}')
print(f'''{'='*30}\ncopy''')
list_a_copy = list_a.copy()
print(f'{list_a_copy}')
print(f'''{'='*30}\ncount''')
list_a.append(1)
list_a.append(1)
list_a.append(1)
list_a.append(1)
print(f'{list_a.count(1)}')
print(f'''{'='*30}\nextend''')
list_b = ['satu', 2, 3+0.j, 4.0]
list_a.extend(list_b)
print(f'{list_a}')
print(f'''{'='*30}\nindex''')
print(f'''{list_a.index('satu')}''')
print(f'''{'='*30}\ninsert''')
list_a.insert(0, 'Ini nilai pertama')
list_a.insert(-1, 'ditaruh diakhir sebelum terakhir')
print(f'{list_a}')
print(f'''{'='*30}\npop''')
print(list_a.pop(0))
print(f'{list_a}')
print(f'''{'='*30}\nremove''')
list_a.remove(3.0)
print(f'{list_a}')
print(f'''{'='*30}\nreverse''')
list_a.reverse()
print(f'{list_a}')
print(f'''{'='*30}\nreverse''')
list_c = [1,8,2,6,2,6,8,3,1,5,7,1,8]
list_c.sort()
print(f'{list_c}')

